function(find_glslc find_result result_path)
	if(WIN32)
		set(bin_name "glslc.exe" PARENT_SCOPE)
	else()
		set(bin_name "glslc" PARENT_SCOPE)
	endif()

	if(EXISTS "${GLSLC_PATH}")
		set(${result_path} "${search_path}" PARENT_SCOPE)
		set(${find_result} TRUE PARENT_SCOPE)
	else()
		if(APPLE)
			set(search_path "${BLIB_PATH}/tools/glslc/Macos")
		elseif(WIN32)
			set(search_path "${BLIB_PATH}/tools/glslc/Windows")
		else()
			set(search_path "${BLIB_PATH}/tools/glslc/Linux")
		endif()

		find_file(glslc "glslc" "${search_path}")
		if(${glslc} STREQUAL "glslc-NOTFOUND")
			set(${find_result} FALSE PARENT_SCOPE)
		else()
			set(${result_path} "${glslc}" PARENT_SCOPE)
			set(${find_result} TRUE PARENT_SCOPE)
		endif()
	endif()
endfunction()
