name: linux-verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: update apt
      run: sudo apt-get update

    - name: package-install
      run: sudo apt-get install libx11-dev xorg-dev freeglut3-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.204.0
        cache: true
      
    - name: configure
      run: cmake -DON_CI=ON -S . -B ./build
      
    - name: make
      run: cd build && cmake --build .

    - name: test
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 &
        build/tests/BLIB.t 
