name: macos-verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
      
    - name: configure
      run: cmake -DON_CI=On -S . -B ./build
      
    - name: make
      run: cd build && cmake --build .
    
    - name: test
      run: build/tests/BLIB.t 
