name: macos-verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
        vulkan-use-cache: true
      
    - name: configure
      run: cmake -DON_CI=On -S . -B ./build
      
    - name: make
      run: cd build && cmake --build .
    
    - name: test
      run: build/tests/BLIB.t 
